### PR TITLE
Add TI-84 Characters

### PR DESCRIPTION
**Pull request by bibbca**
Adding:
- STO arrow
- sub10
- dash (negative sign)
- theta
- pi
- tick (graphing + point)
- degree
- square
- alpha (symbol for letter input)
- 2nd (up arrow for 2nd function)
- geq (Greater than)
- leq (Less Than)
- c3 (superscript 3)
- transpose (superscript T for matrix transpose)
- upr (superscript r)
- chi (lowercase greek letter chi)
- fwedge (wedge pointing right)
- bwedge (wedge pointing left)
- upwedge (wedge pointing upwards)
- Fcdf (styled F)
- Sigma (capital greek letter Sigma)
- eta (lowercase greek letter eta)
- bbN (blackboard N)
- bb/ (blackboard /)
- ell (ellipses)
- ' (single quote)
- L (capital subscript L for lists)
- _ (underscore)

### CODE REVIEW

**Comment by bibbca** [comment]
Found an error with List L command

**Comment by T3SQ8** [comment]
Why did you close down the PR? I'm still open to merging it if you decide to reopen it.

**Comment by bibbca** [comment]
I haven't fixed the list L command, but the other commands work pretty well.

**Comment by T3SQ8** [comment]
The changes have been merged into the main branch. Thanks for the help.

Note: Please set your text editor to avoid switching a file's line-termination to avoid diffs from looking like [this](https://github.com/T3SQ8/tiscreen/pull/1/commits/7785ddda309a009f85f2bc71f2681fa533e570d3#diff-f22a2d9c20da3b4a104b7def8364a4f0c4d2942981e4528f7f410d1b2cfea8b8).

**Pull request merged**
